apiVersion: v1
kind: Service
metadata:
  name: greetings-web-service
  labels:
    app: greetings-web
spec:
  selector:
    app: greetings-web
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005