apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.label }}
spec:
  selector:
    app: {{ .Values.name }}
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30004