apiVersion: apps/v1
kind: Deployment
metadata:
  name: greetings-api
  labels:
    app: greetings
spec:
  selector:
    matchLabels:
      app: greetings-api
  replicas: 2
  template:
    metadata:
      name: greetings-api
      labels:
        app: greetings-api
    spec:
      containers:
        - name: greetings-api
          image: amulrajesh/greetings-api:0.0.1-SNAPSHOT
          env:
            - name: name
              value: Rajesh