apiVersion: v1
kind: Service
metadata:
  name: greetings-api-service
  labels:
    app: greetings
spec:
  selector:
    app: greetings-api
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30004